import { useEffect, useState } from 'react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export function ModelCard() {
  const [metrics, setMetrics] = useState({ status: 'loading' });
  useEffect(() => { fetch(`${API}/api/model-card`).then((response) => response.json()).then(setMetrics).catch(() => setMetrics({ status: 'unavailable' })); }, []);
  const matrix = metrics.confusion_matrix || [];
  const labels = metrics.labels || ['Wake', 'N1', 'N2', 'N3', 'REM'];
  return <div className="model-page"><div className="model-intro"><span className="section-kicker">DOCUMENTATION / MODEL CARD</span><h2>Simple enough to trust.</h2><p>The model uses normalized Welch bandpower features and a RandomForest trained on subject-separated Sleep-EDF epochs. Run the training command to replace the transparent fallback with the serialized artifact.</p></div><div className="model-stats"><div><b>{metrics.subjects || 197}</b><span>Sleep-EDF recordings</span></div><div><b>5</b><span>Sleep stage classes</span></div><div><b>70 / 15 / 15</b><span>Subject-level split</span></div></div><div className="validation-panel"><div><span className="section-kicker">HELD-OUT VALIDATION</span><h3>{metrics.status === 'trained' ? 'Test-set performance' : 'Training pending'}</h3></div>{metrics.status === 'trained' ? <div className="metric-row"><span>Balanced accuracy <b>{(metrics.balanced_accuracy * 100).toFixed(1)}%</b></span><span>Macro F1 <b>{(metrics.macro_f1 * 100).toFixed(1)}%</b></span></div> : <p className="muted">{metrics.message || 'Metrics will appear after the Sleep-EDF training workflow completes.'}</p>}</div>{matrix.length > 0 && <div className="confusion"><div className="panel-head"><div><span className="section-kicker">ERROR ANALYSIS</span><h3>Confusion matrix</h3></div><span className="hint">Rows: true · columns: predicted</span></div><div className="matrix" style={{ '--matrix-size': labels.length }}>{matrix.flatMap((row, rowIndex) => row.map((value, columnIndex) => <span key={`${rowIndex}-${columnIndex}`} style={{ opacity: value ? Math.max(.18, value / Math.max(...matrix.flat())) : .05 }}>{value}</span>))}</div><div className="matrix-labels">{labels.map((label) => <span key={label}>{label}</span>)}</div></div>}<div className="failure-list"><h3>Known failure modes</h3><p><strong>N1 ambiguity</strong> Transitional epochs have weak, mixed signatures and are commonly confused with Wake or N2.</p><p><strong>Movement artifacts</strong> High-amplitude EMG bursts can dominate spectral power and trigger the quality gate.</p><p><strong>Device shift</strong> Electrode placement and amplifier characteristics vary across labs; recalibration is required before clinical use.</p></div></div>;
}
